
development:
 adapter: mysql2
 database: beneshare_dev
 encoding: utf8
 username: root
 password:
 host: localhost
 socket: /tmp/mysql.sock

test:
 adapter: mysql2
 database: beneshare_test
 encoding: utf8
 username: root
 password:
 host: localhost
 socket: /tmp/mysql.sock

production:
 adapter: postgresql
 database: beneshare_prod
 encoding: utf8
 username: root
 password:
 host: localhost
 socket: /tmp/mysql.sock
